# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('big', models.CharField(max_length=200)),
                ('assistant_big', models.CharField(max_length=200)),
                ('big_2', models.CharField(max_length=200)),
                ('assistant_big_2', models.CharField(max_length=200)),
            ],
        ),
    ]
