# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180115_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='big',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('name', 'big')]),
        ),
    ]
